### ISSUE TITLE
Customize morning/night time?

### ISSUE THREAD

**Issue by roblourens** [gokulkrishh/vscode-night-mode#1]
Would be great if I could customize the morning/night time that the theme switches over, so that it matches Flux. I like it to go earlier in the winter and later in the summer.

**Comment by gokulkrishh** [comment]
@roblourens Yes. I have that on my todo. I will do it next version. Thanks for suggesting 👍

**Comment by gokulkrishh** [comment]
@roblourens I have updated the extension to have custom `sunset` & `sunrise` time in 24hrs format. Update your extension

https://github.com/gokulkrishh/vscode-night-mode#before-activating-extension
