### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dobbbri** [gokulkrishh/vscode-night-mode#2]
please fix, 

not change theme automatically

my settings

// Custom theme
"nightMode.sunRise": "Dobri Next -A08- Midnight"
"nightMode.sunRise": "6"
"nightMode.sunSet": "18"

**Comment by gokulkrishh** [comment]
@sldobri I will look into it. Thanks 👍

**Comment by gokulkrishh** [comment]
@sldobri Hey, working on it. Just a head ups. Got busy with work.
