### ISSUE TITLE
Have a look at

### ISSUE THREAD

**Issue by muuvmuuv** [gokulkrishh/vscode-night-mode#3]
I made a similar extension: [Sundial](https://marketplace.visualstudio.com/items?itemName=muuvmuuv.vscode-sundial)
Maybe you want to contribute if it does not fit your needs? Just that you don't waste time on something that is already in the marketplace :)

**Comment by gokulkrishh** [comment]
@muuvmuuv Hey, I like this `sundail`. Seems neat. Will take a look at the issues

**Comment by gokulkrishh** [comment]
@muuvmuuv ALso this ext is no longer maintained.
